language: node_js
node_js:
  - '6'
  - '7'
  - '8'
before_script:
  - yarn install
  - lerna bootstrap
script:
  - cd packages/server && yarn test
  - cd ../ui && yarn test
  #- npm run test-cover
#after_success:
#  - npm run coveralls


